multiverse:
  length_unit: m
  angle_unit: rad
  force_unit: N
  time_unit: s
  handedness: rhs
  root_frame_id: map

  send:
    body: [position, quaternion]
    joint: [joint_rvalue, joint_tvalue]

  # receive:
  #   tiago_dual: [relative_velocity]

  services:
    query_data:
      port: 7400

  publishers:
    tf:
      port: 7300
      rate: 60

  subscribers:
    cmd_vel:
      port: 7200
      body: tiago_dual