multiverse:
  length_unit: m
  angle_unit: rad
  force_unit: N
  time_unit: s
  handedness: rhs
  root_frame_id: map

  publishers:
    tf:
      port: 7300
      rate: 60

  services:
    query_data:
      port: 7400